# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-18 08:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internet_shop', '0003_remove_order_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='goods',
        ),
    ]
