# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-08 22:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('internet_shop', '0005_auto_20180107_0517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='color',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='good', to='internet_shop.Colors'),
        ),
    ]
