# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-13 13:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('internet_shop', '0006_auto_20180108_2207'),
    ]

    operations = [
        migrations.CreateModel(
            name='Options',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(blank=True, choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=140)),
                ('color', models.ManyToManyField(blank=True, default=None, null=True, related_name='good', to='internet_shop.Colors')),
            ],
        ),
        migrations.RemoveField(
            model_name='good',
            name='color',
        ),
        migrations.RemoveField(
            model_name='good',
            name='size',
        ),
        migrations.AddField(
            model_name='good',
            name='options',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='good', to='internet_shop.Options'),
            preserve_default=False,
        ),
    ]
