# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-13 17:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('internet_shop', '0009_auto_20180113_1829'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Size',
            new_name='Sizes',
        ),
        migrations.RenameField(
            model_name='good',
            old_name='size',
            new_name='sizes',
        ),
        migrations.AddField(
            model_name='userbasketitems',
            name='color',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='color_in_basket', to='internet_shop.Colors'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userbasketitems',
            name='size',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='size_in_basket', to='internet_shop.Sizes'),
            preserve_default=False,
        ),
    ]
